"""changing the payment id to become nullable

Revision ID: 25936634cd26
Revises: 90b90e40f53d
Create Date: 2026-06-26 21:16:41.252135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25936634cd26'
down_revision: Union[str, Sequence[str], None] = '90b90e40f53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
