"""changes the payment id to null and making the payment mode be unnullable

Revision ID: 55c050e68c29
Revises: 25936634cd26
Create Date: 2026-06-26 21:39:45.202706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c050e68c29'
down_revision: Union[str, Sequence[str], None] = '25936634cd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'payment_mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
