"""New table is created shows

Revision ID: 7596f1b84a19
Revises: 38b63185bb4f
Create Date: 2026-06-25 20:33:52.664819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7596f1b84a19'
down_revision: Union[str, Sequence[str], None] = '38b63185bb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.Integer(), nullable=False),
    sa.Column('date_scheduled', sa.Date(), nullable=False),
    sa.Column('time_scheduled', sa.Time(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('screen_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
